apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    creation_method: manual
    env: tst
spec:
  containers:
  - image: ilyes512/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
